
auth.token=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

defaults.org=evaluator
defaults.project=react-native

defaults.url=https://sentry.io/
